theloop/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from config import settings
from store.views import *
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

theloop/store/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('category/<slug:cat_slug>/', CategoryView.as_view(), name='category'),
    path('collection/<slug:col_slug>/', CollectionView.as_view(), name='collection'),
    path('item/<slug:item_slug>/', ShowItem.as_view(), name='detail'),
    path('about/', About, name="about"),
    path('register/', RegisterUser.as_view(), name="register"),
    path('login/', LoginUser.as_view(), name="login"),
    path('logout/', logout_user, name="logout"),
    path('bascet/', BascetView.as_view(), name="bascet"),
    path('saveorder/', saveorder, name="saveorder"),
    path('payment/', payment, name='payment')

]

theloop/store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Clothes(models.Model):
    name = models.CharField(max_length=100, verbose_name="Заголовок")
    collection = models.ForeignKey('Collection', on_delete=models.PROTECT, null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    color = models.CharField(max_length=30, verbose_name="Цвет")
    price = models.PositiveIntegerField(verbose_name="Цена")
    discount = models.IntegerField(default=0, verbose_name="Скидка в процентах")
    pricedisc = models.IntegerField(auto_created=True, default=0, verbose_name="Цена со скидкой")
    photo = models.ImageField(upload_to="article/", verbose_name="Фото")
    content = models.TextField(default="", blank=True, verbose_name="Описание")
    size = models.PositiveIntegerField(verbose_name="Размер")
    is_published = models.BooleanField(default=True, verbose_name="Выставить")
    quantity = models.PositiveIntegerField(default=0, blank=True, verbose_name="Остаток на складе")
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name="Категории")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    def __str__(self):
        return self.name + ' ' + self.color

    def get_absolute_url(self):
        return reverse('detail', kwargs={'item_slug': self.slug})

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['time_create']


class Collection(models.Model):
    name = models.CharField(max_length=100, verbose_name="Коллекция")
    slug = models.SlugField(max_length=100, unique=True, db_index=True, verbose_name="URL")
    discount = models.IntegerField(default=0, verbose_name="Скидка на коллекцию")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('collection', kwargs={'col_slug': self.slug})

    class Meta:
        verbose_name = 'Коллекция'
        verbose_name_plural = 'Коллекции'
        ordering = ['-id']


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name="Категория")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    discount = models.IntegerField(default=0, verbose_name="Скидка на каталог")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']


class Provider(models.Model):
    name = models.CharField(max_length=150, verbose_name="Поставщик")
    slug = models.SlugField(max_length=150, unique=True, db_index=True, verbose_name="URL")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'
        ordering = ['id']


class ArticleForShip(models.Model):
    clothes = models.ForeignKey('Clothes', on_delete=models.PROTECT, verbose_name="Одежда")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    shipment = models.ForeignKey('Shipment', on_delete=models.PROTECT)

    def __str__(self):
        return self.clothes.name + str(self.quantity)

    class Meta:
        verbose_name = 'Артикль поставки'
        verbose_name_plural = 'Артикли поставок'
        ordering = ['-id']


class Shipment(models.Model):
    provider = models.ForeignKey('Provider', on_delete=models.PROTECT, verbose_name="Поставщик")
    date = models.DateTimeField(auto_now_add=True, verbose_name="Дата поставки")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    is_took = models.BooleanField(default=False, verbose_name="Оприходован")

    def __str__(self):
        return self.provider.name + str(self.date)

    class Meta:
        verbose_name = 'Поставка'
        verbose_name_plural = 'Поставки'
        ordering = ['id']


class ArticleForOrd(models.Model):
    clothes = models.ForeignKey('Clothes', on_delete=models.PROTECT, verbose_name="Одежда")
    quantity = models.PositiveIntegerField(default=0, blank=True, verbose_name="Количество")
    order = models.ForeignKey('Orders', null=True, on_delete=models.PROTECT)

    def __str__(self):
        return self.clothes.name + str(self.quantity)

    class Meta:
        verbose_name = 'Артикль покупки'
        verbose_name_plural = 'Артикли покупок'
        ordering = ['-id']


class Orders(models.Model):
    date = models.DateTimeField(auto_now_add=True, verbose_name="Дата покупки")
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Покупатель")
    is_paid = models.BooleanField(default=False, verbose_name="Оплата")
    is_took = models.BooleanField(default=False, verbose_name="Получен")

    def __str__(self):
        return self.user.username + str(self.date)

    class Meta:
        verbose_name = 'Покупка'
        verbose_name_plural = 'Покупки'
        ordering = ['is_took', 'id']

theloop/store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Orders


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

theloop/store/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.db.models import F
from django.http import HttpResponseNotFound
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView

from .forms import RegisterUserForm, LoginUserForm
from .models import Clothes, Category, Orders, ArticleForOrd
from .utils import DataMixin


# Create your views here.


class IndexView(DataMixin, ListView):
    model = Clothes
    template_name = "store/index.html"
    context_object_name = 'clothes'

    def get_context_data(self, *, object_list=None, **kwargs):
        pricesdisc = [0, 0, 0, 0]
        context = super().get_context_data(**kwargs)
        # allclothes = Clothes.objects.all()
        # for clothes in allclothes:
        #     if clothes.collection:
        #         clothes.pricedisc = clothes.price * (100 - max(clothes.discount, clothes.cat.discount, clothes.collection.discount))/100
        #     else:
        #         clothes.pricedisc = clothes.price * (100 - max(clothes.discount, clothes.cat.discount))/100
        #         clothes.save()
        first4 = Clothes.objects.filter(quantity__gte=1, is_published=True).order_by('-discount')[:4]
        c_def = self.get_user_context(title="Главная страница", first4=first4, pricesdisc=pricesdisc)
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        return Clothes.objects.filter(
            quantity__gte=1, is_published=True
        ).order_by('-time_update')


class CollectionView(DataMixin, ListView):
    model = Clothes
    template_name = "store/category.html"
    slug_url_kwarg = 'col_slug'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Коллекция")
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        return Clothes.objects.filter(
            quantity__gte=1, is_published=True, collection__slug=self.kwargs['col_slug']
        ).order_by('-time_update')


class CategoryView(DataMixin, ListView):
    model = Clothes
    template_name = "store/category.html"
    slug_url_kwarg = 'cat_slug'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Категории")
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        return Clothes.objects.filter(
            quantity__gte=1, is_published=True, cat__slug=self.kwargs['cat_slug']
        ).order_by('-time_update')


class ShowItem(DataMixin, DetailView):
    model = Clothes

    template_name = 'store/item.html'
    slug_url_kwarg = 'item_slug'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # form_class = OrdersUserForm
        c_def = self.get_user_context(title="Главная страница", ) #form=form_class)
        return dict(list(context.items()) + list(c_def.items()))


def About(request):
    return render(request, 'store/about.html')


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Регистрация")
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизация")
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return redirect('login')


class BascetView(DataMixin, ListView):
    model = Clothes
    template_name = 'store/bascet.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user_ord = Orders.objects.get(user=self.request.user, is_paid=False)
        elements = user_ord.articleforord_set.all()
        money = 0
        for el in elements:
            if el.clothes.pricedisc:
                money += el.clothes.pricedisc * el.quantity
            else:
                money += el.clothes.price * el.quantity
        c_def = self.get_user_context(title="Авторизация", elements=elements, money=money)
        return dict(list(context.items()) + list(c_def.items()))


def saveorder(request):
    quant = request.POST['quantity']
    prod = Clothes.objects.get(slug=request.POST['prod'])
    order = request.user.orders_set.order_by('date').last()

    if not order or order.is_paid:
        order = Orders.objects.create(user=request.user)
    else:
        art = order.articleforord_set.filter(clothes__slug=prod.slug).last()
        if art:
            quant1 = int(quant) + art.quantity
            if quant1 > prod.quantity:
                return already(request, "Вы уже добавили в корзину максимальное количество данного товара")
            art.quantity = quant1
            art.save()
            return redirect('detail', item_slug=prod.slug)
    element = ArticleForOrd.objects.create(clothes=prod, order=order, quantity=quant)
    element.save()
    return redirect('detail', item_slug=prod.slug)


def payment(request):

    ord = request.user.orders_set.get(user=request.user, is_paid=False)
    cloth = ord.articleforord_set.all()
    for cl in cloth:
        cl.clothes.quantity -= cl.quantity
        cl.clothes.save()
    ord.is_paid = True
    ord.save()
    return redirect('home')

def already(request, str):
    context = {'exeption': str, }
    return render(request, 'store/mistake.html', context)

theloop/store/templates/store/about.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 style="font-size: 25px">О нас</h1>
</div>

{% endblock %}

theloop/store/templates/store/bascet.html
{% extends 'base.html' %}

{% block content %}
<section class="catalog">
    <div class="container">
        <div class="products">
            <ul class="products-with-cut">
                {% for p in elements %}
                    <li class="product_in_list">

                        <a href="{{ p.clothes.get_absolute_url }}"><div class="photo" style="background-image: url({{ p.clothes.photo.url }});"></div></a>
                        <div class="info">
                            <a href="{{ p.clothes.get_absolute_url }}"><p class="title-clothes">{{ p.clothes.name }}</p></a>

                            <p class="price">{% if p.clothes.pricedisc %}<span class="old-price">{{ p.clothes.price }}</span>  {{ p.clothes.pricedisc }}
                            {% else %}<span class="norm-price">{{ p.clothes.price }}</span>
                            {% endif %}</p>
                            <p class="number">Количество: {{ p.quantity }}</p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="info">
            <h2>Общая стоимость: {{ money }}</h2>
            <form action="{% url 'payment' %}">
                <input type="hidden" value="{{ money }}" name="price">
                <button type="submit">Оплатить</button>
            </form>
        </div>
    </div>
</section>

{% endblock %}

theloop/store/templates/store/category.html
{% extends 'base.html' %}

{% block content %}
<section class="catalog">
    <div class="container">
        <div class="products">
            <ul class="products-with-cut">
                {% for p in clothes_list %}
                    <li class="product_in_list">

                        <a href="{{ p.get_absolute_url }}"><div class="photo" style="background-image: url({{ p.photo.url }});"></div></a>
                        <div class="info">
                            <a href="{{ p.get_absolute_url }}"><p class="title-clothes">{{ p.name }}</p></a>

                            <p class="price">{% if p.pricedisc %}<span class="old-price">{{ p.price }}</span>  {{ p.pricedisc }}
                            {% else %}<span class="norm-price">{{ p.price }}</span>
                            {% endif %}</p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</section>
{% endblock %}

theloop/store/templates/store/collection.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

theloop/store/templates/store/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="container">
    <div class="promo">
        <div class="main-slide">
            {% for p in first4 %}
            <div class="main-slide-eeee">
                <div class="promo-content">
                    <span>Зимняя распродажа</span>
                    <h2>СКИДКИ ДО {{p.discount}}%</h2>
                    <a class="btn" href="{{ p.get_absolute_url }}">СМОТРЕТЬ МОДЕЛИ</a>
                </div>
                <div class="promo-picture">
                    <img src="{{p.photo.url}}" alt="new shoes">

                    <span class="header-old_price" >{{p.price}} ₽</span>
                    <h2 class="header-new_price">{{ p.pricedisc }} ₽</h2>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="controls">
            {% for p in first4 %}
            <button class="btn_ul" data-num="{{ forloop.counter0 }}"></button>
            {% endfor %}
        </div>

    </div>
</div>
<script src="{% static 'js/list.js' %}"></script>
{% endblock %}

theloop/store/templates/store/item.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="f-box">
        <div class="galerry">
            <img src="{{ post.photo.url }}" alt="">
        </div>
        <div class="other">
            <h2>{{ post.name }}</h2>
            <p class="color">Цвет: {{ post.color }}</p>
            <p class="price">Цена: {% if post.pricedisc %}<span class="old-price">{{ post.price }}</span>  {{ post.pricedisc }}
                            {% else %}<span class="norm-price">{{ post.price }}</span>
                            {% endif %}</p>
            {% if request.user.is_authenticated %}
            <form method="post" action="/saveorder/">
                {% csrf_token %}
            <input type="hidden" value="{{ post.slug }}" name="prod">
                <style>
#id_quantity {
  all: unset;
  -moz-appearance: textfield;
  width: 3em;
  text-align: center;
}
#id_quantity::-webkit-inner-spin-button {
  display: none;
}
</style>
            <p><label class="form-label" for="id_quantity">Количество: </label><br>
            <button type="button" onclick="this.nextElementSibling.stepDown()">-</button>
            <input type="number" name="quantity" min="1" max="{{ post.quantity }}" value="1" readonly id="id_quantity">
            <button type="button" onclick="this.previousElementSibling.stepUp()">+</button>
            </p>

                <button type="submit">В корзину</button>
            </form>
        {% else %}
                <a href="{% url 'register' %}"><button type="submit">Необходимо войти</button></a>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

theloop/store/templates/store/mistake.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<h1>{{exeption}}</h1>
</div>
{% endblock %}